name: Upload Installer to DO Spaces

on:
    push:
        branches:
            - main
        paths:
            - "install.sh" # Only trigger when install.sh changes

jobs:
    upload:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.SPACES_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.SPACES_SECRET_KEY }}
                  aws-region: us-east-1 # DigitalOcean requires this even though it's not used
                  endpoint-url: https://${{ secrets.SPACES_REGION }}.digitaloceanspaces.com

            - name: Upload to Bucket
              run: |
                  aws s3 cp install.sh s3://${{ secrets.SPACES_BUCKET }}/install.sh \
                    --endpoint=https://${{ secrets.SPACES_REGION }}.digitaloceanspaces.com \
                    --acl public-read \
                    --content-type "text/x-sh"
