name: Upload Installer to DO Spaces

on:
  push:
    branches:
      - main
    paths:
      - 'install.sh'

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.SPACES_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.SPACES_SECRET_KEY }}
          aws configure set default.region us-east-1
          aws configure set default.s3.endpoint https://${{ secrets.SPACES_REGION }}.digitaloceanspaces.com

      - name: Upload to DigitalOcean Spaces
        run: |
          aws s3 cp install.sh s3://${{ secrets.SPACES_BUCKET }}/install.sh \
            --endpoint=https://${{ secrets.SPACES_REGION }}.digitaloceanspaces.com \
            --acl public-read \
            --content-type "text/x-sh"
